# Generated by Django 4.2.19 on 2025-02-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
