# Generated by Django 4.2.19 on 2025-02-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_alter_blog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='about',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
