# Generated by Django 4.2.19 on 2025-02-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_alter_blog_about_alter_blog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='about',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
